### ISSUE TITLE
Issue getting my Enviline in HASSIO

### ISSUE THREAD

**Issue by Railittle** [stefanlaheij/ha-buderus#2]
Hello Stefan,
Can you help me with the config off the HA-Buderus in HASSIO. It does't work yet.
Or is this not working anymore?

I get these errors of all the sensors:

018-07-23 21:23:11 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sensor.buderus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-07-23 21:23:13 WARNING (MainThread) [homeassistant.loader] You are using a custom component for buderus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-07-23 21:23:16 ERROR (SyncWorker_10) [custom_components.buderus] Buderus error happened while reading JSON data b'(C\x99\xc6\xa84\xa0\x8ah\xb1\xf2O\xf2\x9e\xf3\xda\xacR=p\xeb\x87\x1b\xd0\x8e\xeaze\x1c\xf4\xd9l\x95\x05\xf1\xd8\xc4\xc6\x19\xc0\x02\n\xb1\xf8\xdc\x07u\x1ew#\xc9\xe2\xd9b#;\x89\xc06__T\x88#\xe9\r\x9b\xcd\xc78Oe2\xc6w\x85\x02Q\x16\xa5J\xd0\x93\x0b\xaa\xf4\xaf\xdc\xe56\xddY\x9f\x11\xa9\xfc2m\xa9\x04\xd3\xb2\x03\x01X\xa9\xc79\x05m\x96k\x04R\xac\x8fp\xd9+\ri\xdc\xc4\x83\x84vT\xb1c\xdef\xf43\xb7d\x97>\x03\xb5pH\xe2_x': 'utf-8' codec can't decode byte 0x99 in position 2: invalid start byte
2018-07-23 21:23:16 ERROR (MainThread) [homeassistant.components.sensor] buderus: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 319, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/buderus.py", line 213, in update
    self._state = self._bridge._get_value(data)
  File "/config/custom_components/buderus.py", line 92, in _get_value
    return j['value']
TypeError: 'bool' object is not subscriptable
2018-07-23 21:23:16 ERROR (SyncWorker_12) [custom_components.buderus] Buderus error happened while reading JSON data b'A\xf9d\xcb5\x10.f\x0b*\xa3<\xb3\x83m\x04\x82\x1a\xe1%\xac\xb2\x8am\x9b\x06\xffF\x9d\x99\xda\xcbd\x81\xcap\x93vw\x10\xec\x17[\x84\xb3!\xed\xc7{\xd3D\x85R\x82\xfe\xa3\x15\x8fj\x91\x94T\xad\xec\xfa\xd7Q.t\xb8\x8b\x9c\xf7D)\xdb@m\x0f\xd3\xd6\x8a1\xfd\x88^\xf6v\xf0\x07)U\x93\xc6v\xf0\xa0\xa6\xf4q\xec\x19\\d\x98\xe4n\xc2\xa8\xa6\x1e\xf5\xd3\x014J\x85#T\x9cq\xea\xa0.\xe1\xc9\xa0\xa9\x03E\xbfy\xd1\x8b\xde\xd1\xae\x17\x9ev+\xe2\x94j\xd1O\xa8.\x1d\xde\x02\x8al\xc1\x0eq\xec\xa4o0\x15\x1f\xd8\xd5,n\xe0S\xc3\xe2\x9b\xf9*\x80;\x91': 'utf-8' codec can't decode byte 0xf9 in position 1: invalid start byte
2018-07-23 21:23:17 ERROR (MainThread) [homeassistant.components.sensor] buderus: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 319, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/buderus.py", line 213, in update
    self._state = self._bridge._get_value(data)
  File "/config/custom_components/buderus.py", line 92, in _get_value
    return j['value']
TypeError: 'bool' object is not subscriptable

**Comment by stefanlaheij** [comment]
Hi, seems like you did not create the password correctly so the message
received from the Buderus is not decrypted correctly.

2018-07-23 21:49 GMT+02:00 Railittle <notifications@github.com>:

**Comment by Railittle** [comment]
Hi Stefan,
Could be. But I've tried several ways of fill in the AES-Key-Generator passwords. On my IP gateway stands a loginname and a password. These info I have used for Benutzer-Passwort (gebruiker paswoord) and Geräte-Passwort (apparaat paswoord). Is this correct? 

Regards,

Raimond

**Comment by stefanlaheij** [comment]
That seems correct. What kind of Enviline do you have?

2018-07-25 19:28 GMT+02:00 Railittle <notifications@github.com>:

**Comment by Railittle** [comment]
I have a nefit enviline  (EnviLine A/W Monoblock 9.0 E-S) model including IP gateway. In procontrol app (IOS) I see Gateway Firmware versie 04.04.05 and Gateway hardware versie iCom_Low_NSC_v1.

I Hope that you can help me because I really want the Heatpump info in HA (Hass.io)

**Comment by moustic999** [comment]
for Nefit you should use : https://github.com/marconfus/ha-nefit

**Comment by Railittle** [comment]
moustic999,

Thx for your reply, but thats something else. I have a Nefit (Bosch) heatpump with an IP gateway. Thats not the thermostat you ment.

I still have the problem that it doesn't work. anybody could help me?

Regards,

R

**Comment by marcews** [comment]
Did  you find a solution Railittle? I am trying to get in contact with my Nefit Enviline (preferrable php) as well without luck...

**Comment by Railittle** [comment]
There are Some people very busy with making a suitable solution. Look here please:

https://github.com/moustic999/bosch-thermostat-http-client-python/issues/6#issuecomment-462060084
