### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by kantorbalazs** [stefanlaheij/ha-buderus#6]
I have changed all neccessary files in the Custom Components folder, but still its not loading, and the sensors are giving me an error if i check the configuration.

**Comment by stefanlaheij** [comment]
What does the log say?

**Comment by kantorbalazs** [comment]
Error loading custom_components.buderus.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/buderus/climate.py", line 6, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)

**Comment by kantorbalazs** [comment]
Now, after trying with your latest update, it works! :) thanks!

**Comment by kantorbalazs** [comment]
Previously I have used a sensor/buderus.py file, which contained more values regarding the system. Maybe you can use it to extend the number of the monitorable components. 
[sensor.zip](https://github.com/stefanlaheij/ha-buderus/files/2956623/sensor.zip)
